#!/bin/bash
cd "${BASH_SOURCE%/*}"

echo '[setup] xdg';

mkdir -p ~/.config
mkdir -p media
mkdir -p media/music
mkdir -p media/documents
mkdir -p media/pictures
mkdir -p media/public
mkdir -p media/videos

cp -v .config/user-dirs.dirs ~/.config/user-dirs.dirs
