#!/bin/bash
cd "${BASH_SOURCE%/*}"

echo '[setup] xf86-input-cmt';

if [ -f /usr/share/X11/xorg.conf.d/50-synaptics.conf ];
then
  sudo mv -v /usr/share/X11/xorg.conf.d/50-synaptics.conf /usr/share/X11/xorg.conf.d/50-synaptics.conf.old
fi

sudo cp -v /usr/share/xf86-input-cmt/50-touchpad-cmt-samus.conf /usr/share/X11/xorg.conf.d/
