#!/bin/bash

url="https://play.spotify.com/"
config="/home/jsl/.config/google-chrome-spotify"

if [ "$1" = "app" ]; then
  google-chrome --app=$url --user-data-dir=$config
else
  google-chrome $url --user-data-dir=$config
fi
