#!/bin/bash
cd "${BASH_SOURCE%/*}"

echo '[install] powerline';

sudo apt-get install python-pip
pip install powerline-status --user

wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf -P ~/.config/fontconfig/conf.d/
wget https://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf -P ~/.fonts/

mkdir -p ~/tmp/powerline-fonts
git clone https://github.com/powerline/fonts ~/tmp/powerline-fonts
bash ~/tmp/powerline-fonts/install.sh
rm -rf ~/tmp/powerline-fonts

fc-cache -vf ~/.fonts/
