#!/bin/bash
cd "${BASH_SOURCE%/*}"

echo '[install] i3';

rm -rf ~/tmp/i3
mkdir ~/tmp/i3 -p
cd ~/tmp/i3
apt-helper download-file http://debian.sur5r.net/i3/pool/main/s/sur5r-keyring/sur5r-keyring_2017.01.02_all.deb keyring.deb SHA256:4c3c6685b1181d83efe3a479c5ae38a2a44e23add55e16a328b8c8560bf05e5f
sudo apt install ./keyring.deb
sudo echo "deb http://debian.sur5r.net/i3/ $(grep '^DISTRIB_CODENAME=' /etc/lsb-release | cut -f2 -d=) universe" >> /etc/apt/sources.list.d/sur5r-i3.list
sudo apt update

sudo apt-get install i3 pavucontrol seahorse lxappearance xfce4-terminal thunar

mkdir -p ~/.fonts
cp -v .fonts/* ~/.fonts
fc-cache -vf ~/.fonts
