#!/bin/bash
cd "${BASH_SOURCE%/*}"

echo '[install] gtk';

rm -rf ~/tmp/gtk
mkdir ~/tmp/gtk -p
cd ~/tmp/gtk

git clone https://github.com/horst3180/arc-icon-theme --depth 1 && cd arc-icon-theme
./autogen.sh --prefix=/usr
sudo make install

cd ../

sudo add-apt-repository ppa:fossfreedom/arc-gtk-theme-daily
sudo apt-get update
sudo apt-get install moka-icon-theme
sudo apt-get install arc-theme

rm -rf ~/tmp/gtk

mkdir -p ~/.fonts
cp -v .fonts/* ~/.fonts
fc-cache -vf ~/.fonts
