#!/bin/bash
cd "${BASH_SOURCE%/*}"

echo '[setup] xfce4';

mkdir -p ~/.bin/
mkdir -p ~/.config/xfce4/xfconf/xfce-perchannel-xml
mkdir -p ~/.config/xfce4/terminal

cp -v .bin/* ~/.bin
cp -v .config/xfce4/xfconf/xfce-perchannel-xml/* ~/.config/xfce4/xfconf/xfce-perchannel-xml
cp -v .config/xfce4/terminal/terminalrc ~/.config/xfce4/terminal/terminalrc
cp -v lockpaper.png ~/lockpaper.png
