#!/bin/bash
PATH=$PATH:$HOME/.bin:$HOME/.local/bin
rofi -show run -lines 3 -eh 2 -opacity "85" -bw 0 -bc "#2f343f" -bg "#2f343f" -fg "#f3f4f5" -hlbg "#2f343f" -hlfg "#9575cd" -font "System San Francisco Display 24" -width 100 -padding 400
