#!/bin/bash
PATH=$PATH:$HOME/.bin:$HOME/.local/bin
rofi -show run -lines 3 -eh 2 -opacity "85" -bw 0  -color-normal "#2f343f,#f3f4f5,#2f343f,#2f343f,#9575cd" -color-window "#2f343f,#2f343f,#2f343f" -font "System San Francisco Display 24" -width 100 -padding 400
