#!/bin/bash

volume=$(amixer -D pulse get Master | grep 'Front Left' | awk '$0~/%/{print $5}' | tr -d '[]');
muted=$(amixer -D pulse get Master | grep 'Front Left' | egrep 'Playback.*?\[o' | egrep -o '\[o.+\]');

if [ "$muted" == "[off]" ]; then
  echo " 0%"
else
  echo " $volume"
fi
